### ISSUE TITLE
Issue with tabs

### ISSUE THREAD

**Issue by bryanwillis** [tmconnect/ACF-Tooltip#5]
Unfortunately it breaks when using tabs... The icons don't show up, but they still work on the other ones. Otherwise this is awesome, as are your other acf plugins!

**Comment by tmconnect** [comment]
I tested this and for me it works as expected.
![tooltip](https://cloud.githubusercontent.com/assets/2598781/10862602/82c4c410-7faf-11e5-9719-8c4a67f09b83.png)

The reason for the error may be caused by another plugin or by the theme. Are you sure you installed the latest version of ACF and the Tooltip plugin. What other plugins are activated and which theme you are using?
